dist: bionic

env:
  global:
    - secure: "qZN8JV91mJz2sLyewz6nRVb++KsNUwstvbMPpion4kfs23m54FgMDI+bpu8pgrZyINqsFwDdKbElnUOjR7tAwtJq5zLeSuC7vy2YT/eud/D3C1kcJBjE4qYihRRRlYMQhlsZb1/3gaN9mvUx0g1UmHLug9SfSy3GFDiSKMeE6umMOLJzLzXl0aOLtREiFZMb8TmvVRzD6W1GuLBe2gxYHvsOKumhVbL0CJnocGzTlSmAgx/smPjMahTznURtmfXpEijh7FBfUz4JRhGSdNjKGLXZ/ci8b1MVYRu1FElkyub/hVgkcJEHbmBeXDQtdTCR6Xp+a4r0vRnroHwfRLHoAfXw7QexJqOZ4Xab91ExFVzHvxvasEcEuUjSMYubnW4InlcxbM7r7lNGRspbbb8FNl3MVcxcYewkafN6tcO/yaHUHyneBaXE8TwqUXwscMFy4N9lRcK2hrUL/505honlAOnABRjav2NhynThX9kBs7Wd3E4eP2kyYwOTYmCmj4n3Ses2kelxfHMq/yXAML29rYurxEcFiOcwTaL5O66wW+ecdb6mhlXyPmS/ypCtlUKOWjs3+5yoSwaT8o+3usgcllIEzStczISKMZ1+Rtgf32o1voJNn0dQSMmMNLV4WRNAl8TZjEjTrY6N2Xz/7xCXPwh+UoCaNaOlaPAYY4v0tcc="
    - secure: "qDtQY9K+4NudgYwSBkIy1FqGENHg/M6qZ1omoYwuybehYL9ejJymXEfAgEbrCWu/8MwTttt4bQGu6B7+2jpYbmkQ1yxyuIgAPoaY7AH6Qw8azs15ERl3gOFMxjQ0mxmzvEKxBhMNSSaWWIkggdx/0naQ4b0hbG7NGVtUaPAwGDBDI7Q/Fg7ufUQRNGtVzxenUWyyaxJfRXYUICYojZgIXbiu/LvwSRGtV8fW0dDoYOJZUyUXfj0WXe6LPax01IJdYYMyRgmjGO2tiPWfBbWtqBgbjZUMkc5hzJE1TZpJglcABmu9OE3BOV80bCm+uyZTnXzUNnffHonKoQL0gEwnS5QA3ol67bbq3AhlM6jTIVoerP9SJhofyy8Xl16v33XvD9rpNBdAY6MppR4WPk3uAYFOCQNYPLBzeM4qKaRlXK05GEKZnPqFVoCCuZOT7xVSuUoFcSnYFEYY6Ng6FppKRxBpaTWdc57cV1zU+we8tkVBEhtZ2YBcxhyUDSUemxbMAEid1OuVH4QOitUXP7NF0jSpgvTQt35kjUTbIgKUTxPJl3KXf3h5b7x2D2VhNV+/V0/dSmupT3qmaWze9x4XU2YO8lgnwSLXNlrRCbDjF0qGrvDicls6BuaAyp62VgUjfL4bYojrYRJ2mAPfWlaQVtnsD31D6I5q9tGVxdYTidw="

branches:
  only:
    - master

stages:
  - test
  - build-go
  - build-docker
  - deploy

jobs:
  include:
  - stage: "test"
    language: go
    go: "1.13"
    install: 
    - go get -v
    script:
    - go test -v
  - stage: "build-go"
    language: go
    go: "1.13"
    install:
    - go get -v
    script:
    - go build -v
  - stage: "build-docker"
    script: 
    - docker build --no-cache -t go-auto-yt:build .
  - stage: "deploy"
    language: shell
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t go-auto-yt .
    - docker tag go-auto-yt xiovv/go-auto-yt:stable
    - docker push xiovv/go-auto-yt:stable

