dist: bionic

env:
  global:
    - secure: "Dl5jOu7Vk+ILEctWPVjsZn8AHkbjbmVKCGiA1iN4XkHgmBMYoh2FMfkSJ7LyziQVrv0IRwIXKX2h5GYQFwYn7cAw3xiUsXiZvAFIoRfwkyfE++Mr4JLX5b0DYQyoCgbnpRVuP9yet41R9A2XXGmvCn2IXfgJrHLuqpRldhHjBCMOymCsb4clL0xw80/NwxC9lSSrNua8GxbP5gksJh9NWKUiuXK8uHx1MyqloxoQQKlPN50ZQadR14DRrZH1uybRCEN/l1hQIlAFpT9mfMzrbHh1zGpi8YmZj8/a6oB3Uqrv8qXWshQ/Y57S8JFExJxQlwERUBxN04d5qecoMOPWV8lx8XKtMvCGrCSG6W23u+KMg8R4VB+TIi3U71zZmjUFvRaDtJ8EUilQbnKW3arOOU+ZhNtOZ2j54tMf2xx2j76rpTNAwKBd0Ma3KOydF0sUZhjKZAkqRej/H/nNElgVF5ORGWd5yeDk6SFWmY985xjachPYPhG8IRe+o5Ipt5Lo23qgozAN8h49NqqT6FSEX5S4By1Xw5tSy717l9VfV/0kr1MnfAcLczcokNTwV9VshSLq8ojulBrXxH6oWzOlpoMZ4fMsSAwr/Z0YL00Ky6tw3RWXXXDdWljEs21EVuHTnDYVtOYNBzqmxwOHpwn4brq644G5ar+t7rejD22TVgs="
    - secure: "IFgbPr/PHut/N8DArYmAR4ejQpLoPCgYel04kgiI++9Q0iW82oD1vODR+k7h7bthR7jyROjTZ7xujapQAqy/vML8nIqqUlpDcNJVtpTVPfMNqQgr1YnjmrsCCjEVIXIX4c2MSLw8xoxh89adl3DqmWISkSy4DFXWHMy+LeZM9mwtNPklZBIjDcxFGfRwtv10KZ7iQzRtzbehZJnguEvrOQ9lZhpCmeGy4+gv5xYtHINQ6LLUYtwg/OfM+kAFiiFlFgp4ZDTJGVACiQgsq4+zMBsSgfYku60iUd7hgZv3i4uRBCx8iafthDsu13GyZqxkF09C9gnGoKUVSZe+EsmGV7cVTzFQf/Hs3df6TV5Dop8IhJ3DcBxrxOKT/bRlgr6AAFpOz9oZMnW5F3GSHIJM8knCqFRtNeKhn6JMwfyrwDfBLR0lQypoAi1AkwrmsKtpVs/2y3J0kDg7x+Xs/HxOVIWJf6KG7dii4j/8urqdX75yOVGnTFuH35qKweGYK52uRHrz6QU/Cxo88PNCGfYKDaL6YxY2BY56lwlfd+38ege/F2rVWA1oSpVspKM8pRvI2ZOD35d2nKWoqPIIT3G3KOQwzogKO3qnLrXMWI1/Jzd8e3mmOUgqOW3TuubTY7HTcKgecYuTP40gPiDeH1ZpJz0XVJltfjQ1jcZRR+/Qlso="

branches:
  only:
    - master

stages:
  - test
  - build-go
  - build-docker
  - deploy

jobs:
  include:
  - stage: "test"
    language: go
    go: "1.13"
    install: 
    - go get -v
    script:
    - go test -v
  - stage: "build-go"
    language: go
    go: "1.13"
    install:
    - go get -v
    script:
    - go build -v
  - stage: "build-docker"
    script: 
    - docker build --no-cache -t go-auto-yt:build .
  - stage: "deploy"
    language: shell
    script:
    - docker build -t go-auto-yt .
    - docker tag go-auto-yt xiovv/go-auto-yt:stable
    - docker push xiovv/go-auto-yt:stable

